FROM maven:3.9-eclipse-temurin-17 AS build
WORKDIR /app
COPY . .
RUN mvn package -pl api-gateway -am -DskipTests

FROM eclipse-temurin:17-jre
COPY --from=build /app/api-gateway/target/api-gateway-*.jar app.jar
EXPOSE 9000
ENTRYPOINT ["java", "-jar", "/app.jar"]