FROM maven:3.9-eclipse-temurin-17 AS build
WORKDIR /app
COPY . .
RUN mvn package -pl media-service -am -DskipTests

FROM eclipse-temurin:17-jre
COPY --from=build /app/media-service/target/media-service-*.jar app.jar
EXPOSE 8083
ENTRYPOINT ["java", "-jar", "/app.jar"]